const NEW_COMMENT = 'NEW_COMMENT'
const DELETE_COMMENT = 'DELETE_COMMENT'
const NEW_POST = 'NEW_POST'
const UPDATE_POST = 'UPDATE_POST'
const DELETE_POST = 'DELETE_POST'

module.exports = {
  NEW_COMMENT,
  DELETE_COMMENT,
  NEW_POST,
  UPDATE_POST,
  DELETE_POST
}
